/**
 * claim_id is ALWAYS generated by the frontend, before the submit_claim
 * signature — never expected back from a transaction, never inferred from
 * "the caller's last claim". This is what gives every claim its own URL
 * from the instant it's created, so two tabs / two wallets / a double click
 * can never collide or overwrite each other.
 *
 * u256, so we generate 32 random bytes and read them as an unsigned
 * big-endian bigint, then carry it as a decimal string (URL- and
 * JSON-safe; convert to BigInt right before passing it as a contract arg).
 */
export function generateClaimId(): string {
  const bytes = new Uint8Array(32);
  if (typeof crypto !== "undefined" && crypto.getRandomValues) {
    crypto.getRandomValues(bytes);
  } else {
    // Extremely defensive fallback; crypto.getRandomValues is available in
    // every modern browser and in Node's Web Crypto, so this should not run.
    for (let i = 0; i < bytes.length; i++) bytes[i] = Math.floor(Math.random() * 256);
  }

  let value = 0n;
  for (const byte of bytes) {
    value = (value << 8n) | BigInt(byte);
  }
  return value.toString();
}

export function isValidClaimId(value: string): boolean {
  if (!/^\d+$/.test(value)) return false;
  try {
    const n = BigInt(value);
    return n >= 0n && n < 2n ** 256n;
  } catch {
    return false;
  }
}
